
export enum ModeStrings {
  DRAW_LINE_STRING="DRAW_LINE_STRING",
  DRAW_POLYGON="DRAW_POLYGON",
  DRAW_POINT="DRAW_POINT",
  SIMPLE_SELECT="SIMPLE_SELECT",
  DIRECT_SELECT="DIRECT_SELECT",
  STATIC="STATIC",
};